//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymWebUI.SR_PettyCash {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_PettyCash.IAPI_PettyCash")]
    public interface IAPI_PettyCash {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI_PettyCash/GetCustomer", ReplyAction="http://tempuri.org/IAPI_PettyCash/GetCustomerResponse")]
        string GetCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI_PettyCash/GetCustomer", ReplyAction="http://tempuri.org/IAPI_PettyCash/GetCustomerResponse")]
        System.Threading.Tasks.Task<string> GetCustomerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPI_PettyCashChannel : SymWebUI.SR_PettyCash.IAPI_PettyCash, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class API_PettyCashClient : System.ServiceModel.ClientBase<SymWebUI.SR_PettyCash.IAPI_PettyCash>, SymWebUI.SR_PettyCash.IAPI_PettyCash {
        
        public API_PettyCashClient() {
        }
        
        public API_PettyCashClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public API_PettyCashClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public API_PettyCashClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public API_PettyCashClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCustomer() {
            return base.Channel.GetCustomer();
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerAsync() {
            return base.Channel.GetCustomerAsync();
        }
    }
}
